### ISSUE TITLE
error: Package ‘emacs-26.3’ is unavailable

### ISSUE THREAD

**Issue by anthrolisp** [alphapapa/alpha-org#1]
I'm on Ubuntu 18.04, running Emacs 26.1.

**Comment by alphapapa** [comment]
You can edit the version in the file to reduce the version number if you like.  I'm using Emacs 26.3 (on an older version of Ubuntu than that), so rather than spend time on making code in this new package compatible with old versions, I'm just working forward.

Or you can easily install a newer version of Emacs, e.g. from Kevin Kelley's PPA repo.  I used his packaging to build 26.3 on my system, but the binary packages should work on yours.

**Comment by anthrolisp** [comment]
Thanks. I've managed to install alpha-org, but the M-SPC key bindings are not working (says "M-SPC is undefined"). I know it's installed since I can call the various packages like org-tree manually through M-x. Any ideas?
